<?php

/**
 * BaseStoryRedirect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $redirect_id
 * @property integer $story_id
 * @property Redirect $Redirect
 * @property Story $Story
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getRedirectId()  Returns the current record's "redirect_id" value
 * @method integer       getStoryId()     Returns the current record's "story_id" value
 * @method Redirect      getRedirect()    Returns the current record's "Redirect" value
 * @method Story         getStory()       Returns the current record's "Story" value
 * @method StoryRedirect setId()          Sets the current record's "id" value
 * @method StoryRedirect setRedirectId()  Sets the current record's "redirect_id" value
 * @method StoryRedirect setStoryId()     Sets the current record's "story_id" value
 * @method StoryRedirect setRedirect()    Sets the current record's "Redirect" value
 * @method StoryRedirect setStory()       Sets the current record's "Story" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoryRedirect extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story_redirect');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('redirect_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('story_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Redirect', array(
             'local' => 'redirect_id',
             'foreign' => 'id'));

        $this->hasOne('Story', array(
             'local' => 'story_id',
             'foreign' => 'id'));
    }
}