<?php

/**
 * BaseStoryComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $story_id
 * @property integer $comment_id
 * @property Story $Story
 * @property Comment $Comment
 * 
 * @method integer      getId()         Returns the current record's "id" value
 * @method integer      getStoryId()    Returns the current record's "story_id" value
 * @method integer      getCommentId()  Returns the current record's "comment_id" value
 * @method Story        getStory()      Returns the current record's "Story" value
 * @method Comment      getComment()    Returns the current record's "Comment" value
 * @method StoryComment setId()         Sets the current record's "id" value
 * @method StoryComment setStoryId()    Sets the current record's "story_id" value
 * @method StoryComment setCommentId()  Sets the current record's "comment_id" value
 * @method StoryComment setStory()      Sets the current record's "Story" value
 * @method StoryComment setComment()    Sets the current record's "Comment" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoryComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story_comment');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('story_id', 'integer', 11, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('comment_id', 'integer', 11, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 11,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Story', array(
             'local' => 'story_id',
             'foreign' => 'id'));

        $this->hasOne('Comment', array(
             'local' => 'comment_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $yiggnotifcation0 = new yiggNotifcation(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($yiggnotifcation0);
    }
}