<?php

/**
 * BaseSystemStats
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $total_user
 * @property integer $total_story
 * @property integer $total_comments
 * @property integer $total_friends
 * @property integer $total_real_friends
 * @property integer $total_groups
 * @property integer $total_group_storys
 * @property integer $total_votes
 * @property integer $total_tags
 * @property timestamp $calculated
 * 
 * @method integer     getId()                 Returns the current record's "id" value
 * @method integer     getTotalUser()          Returns the current record's "total_user" value
 * @method integer     getTotalStory()         Returns the current record's "total_story" value
 * @method integer     getTotalComments()      Returns the current record's "total_comments" value
 * @method integer     getTotalFriends()       Returns the current record's "total_friends" value
 * @method integer     getTotalRealFriends()   Returns the current record's "total_real_friends" value
 * @method integer     getTotalGroups()        Returns the current record's "total_groups" value
 * @method integer     getTotalGroupStorys()   Returns the current record's "total_group_storys" value
 * @method integer     getTotalVotes()         Returns the current record's "total_votes" value
 * @method integer     getTotalTags()          Returns the current record's "total_tags" value
 * @method timestamp   getCalculated()         Returns the current record's "calculated" value
 * @method SystemStats setId()                 Sets the current record's "id" value
 * @method SystemStats setTotalUser()          Sets the current record's "total_user" value
 * @method SystemStats setTotalStory()         Sets the current record's "total_story" value
 * @method SystemStats setTotalComments()      Sets the current record's "total_comments" value
 * @method SystemStats setTotalFriends()       Sets the current record's "total_friends" value
 * @method SystemStats setTotalRealFriends()   Sets the current record's "total_real_friends" value
 * @method SystemStats setTotalGroups()        Sets the current record's "total_groups" value
 * @method SystemStats setTotalGroupStorys()   Sets the current record's "total_group_storys" value
 * @method SystemStats setTotalVotes()         Sets the current record's "total_votes" value
 * @method SystemStats setTotalTags()          Sets the current record's "total_tags" value
 * @method SystemStats setCalculated()         Sets the current record's "calculated" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSystemStats extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('system_stats');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('total_user', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('total_story', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('total_comments', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('total_friends', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('total_real_friends', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('total_groups', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('total_group_storys', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('total_votes', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('total_tags', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('calculated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}