<?php

/**
 * BaseStoryRender
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $story_id
 * @property integer $user_id
 * @property timestamp $created_at
 * @property float $epoch_time
 * @property Story $Story
 * @property User $User
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method integer     getStoryId()    Returns the current record's "story_id" value
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method timestamp   getCreatedAt()  Returns the current record's "created_at" value
 * @method float       getEpochTime()  Returns the current record's "epoch_time" value
 * @method Story       getStory()      Returns the current record's "Story" value
 * @method User        getUser()       Returns the current record's "User" value
 * @method StoryRender setId()         Sets the current record's "id" value
 * @method StoryRender setStoryId()    Sets the current record's "story_id" value
 * @method StoryRender setUserId()     Sets the current record's "user_id" value
 * @method StoryRender setCreatedAt()  Sets the current record's "created_at" value
 * @method StoryRender setEpochTime()  Sets the current record's "epoch_time" value
 * @method StoryRender setStory()      Sets the current record's "Story" value
 * @method StoryRender setUser()       Sets the current record's "User" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoryRender extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story_render');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('story_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'notnull' => true,
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('epoch_time', 'float', null, array(
             'notnull' => true,
             'type' => 'float',
             ));


        $this->index('story_render_created_at', array(
             'fields' => 'created_at',
             ));
        $this->index('story_render_epoch_time', array(
             'fields' => 'epoch_time',
             'sorting' => 'DESC',
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Story', array(
             'local' => 'story_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $yiggepoch0 = new yiggEpoch();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($yiggepoch0);
        $this->actAs($timestampable0);
    }
}