<?php

/**
 * BaseUserSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $comment_notify
 * @property boolean $comment_email
 * @property boolean $pm_email
 * @property boolean $show_awards
 * @property boolean $display_help
 * @property boolean $twitterized
 * @property string $twitter_hash
 * @property boolean $tweet_stories
 * @property string $city
 * @property string $country
 * @property string $occupation
 * @property enum $sex
 * @property timestamp $birthday
 * @property string $website
 * @property string $blog
 * @property timestamp $last_sms
 * @property string $mailbox_name
 * @property boolean $use_toolbar
 * @property string $twitter_name
 * 
 * @method integer      getId()             Returns the current record's "id" value
 * @method boolean      getCommentNotify()  Returns the current record's "comment_notify" value
 * @method boolean      getCommentEmail()   Returns the current record's "comment_email" value
 * @method boolean      getPmEmail()        Returns the current record's "pm_email" value
 * @method boolean      getShowAwards()     Returns the current record's "show_awards" value
 * @method boolean      getDisplayHelp()    Returns the current record's "display_help" value
 * @method boolean      getTwitterized()    Returns the current record's "twitterized" value
 * @method string       getTwitterHash()    Returns the current record's "twitter_hash" value
 * @method boolean      getTweetStories()   Returns the current record's "tweet_stories" value
 * @method string       getCity()           Returns the current record's "city" value
 * @method string       getCountry()        Returns the current record's "country" value
 * @method string       getOccupation()     Returns the current record's "occupation" value
 * @method enum         getSex()            Returns the current record's "sex" value
 * @method timestamp    getBirthday()       Returns the current record's "birthday" value
 * @method string       getWebsite()        Returns the current record's "website" value
 * @method string       getBlog()           Returns the current record's "blog" value
 * @method timestamp    getLastSms()        Returns the current record's "last_sms" value
 * @method string       getMailboxName()    Returns the current record's "mailbox_name" value
 * @method boolean      getUseToolbar()     Returns the current record's "use_toolbar" value
 * @method string       getTwitterName()    Returns the current record's "twitter_name" value
 * @method UserSettings setId()             Sets the current record's "id" value
 * @method UserSettings setCommentNotify()  Sets the current record's "comment_notify" value
 * @method UserSettings setCommentEmail()   Sets the current record's "comment_email" value
 * @method UserSettings setPmEmail()        Sets the current record's "pm_email" value
 * @method UserSettings setShowAwards()     Sets the current record's "show_awards" value
 * @method UserSettings setDisplayHelp()    Sets the current record's "display_help" value
 * @method UserSettings setTwitterized()    Sets the current record's "twitterized" value
 * @method UserSettings setTwitterHash()    Sets the current record's "twitter_hash" value
 * @method UserSettings setTweetStories()   Sets the current record's "tweet_stories" value
 * @method UserSettings setCity()           Sets the current record's "city" value
 * @method UserSettings setCountry()        Sets the current record's "country" value
 * @method UserSettings setOccupation()     Sets the current record's "occupation" value
 * @method UserSettings setSex()            Sets the current record's "sex" value
 * @method UserSettings setBirthday()       Sets the current record's "birthday" value
 * @method UserSettings setWebsite()        Sets the current record's "website" value
 * @method UserSettings setBlog()           Sets the current record's "blog" value
 * @method UserSettings setLastSms()        Sets the current record's "last_sms" value
 * @method UserSettings setMailboxName()    Sets the current record's "mailbox_name" value
 * @method UserSettings setUseToolbar()     Sets the current record's "use_toolbar" value
 * @method UserSettings setTwitterName()    Sets the current record's "twitter_name" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserSettings extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_settings');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('comment_notify', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('comment_email', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('pm_email', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('show_awards', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('display_help', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('twitterized', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('twitter_hash', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('tweet_stories', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('city', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('country', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('occupation', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('sex', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'male',
              1 => 'female',
              2 => 'none',
             ),
             ));
        $this->hasColumn('birthday', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('website', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('blog', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('last_sms', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('mailbox_name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('use_toolbar', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('twitter_name', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}