<?php

/**
 * BaseFeedEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property integer $feed_id
 * @property string $link
 * @property string $long_link
 * @property timestamp $added_at
 * @property string $description
 * @property float $epoch_time
 * @property timestamp $created
 * @property boolean $in_newsroom
 * @property Feed $Feed
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getTitle()       Returns the current record's "title" value
 * @method integer   getFeedId()      Returns the current record's "feed_id" value
 * @method string    getLink()        Returns the current record's "link" value
 * @method string    getLongLink()    Returns the current record's "long_link" value
 * @method timestamp getAddedAt()     Returns the current record's "added_at" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method float     getEpochTime()   Returns the current record's "epoch_time" value
 * @method timestamp getCreated()     Returns the current record's "created" value
 * @method boolean   getInNewsroom()  Returns the current record's "in_newsroom" value
 * @method Feed      getFeed()        Returns the current record's "Feed" value
 * @method FeedEntry setId()          Sets the current record's "id" value
 * @method FeedEntry setTitle()       Sets the current record's "title" value
 * @method FeedEntry setFeedId()      Sets the current record's "feed_id" value
 * @method FeedEntry setLink()        Sets the current record's "link" value
 * @method FeedEntry setLongLink()    Sets the current record's "long_link" value
 * @method FeedEntry setAddedAt()     Sets the current record's "added_at" value
 * @method FeedEntry setDescription() Sets the current record's "description" value
 * @method FeedEntry setEpochTime()   Sets the current record's "epoch_time" value
 * @method FeedEntry setCreated()     Sets the current record's "created" value
 * @method FeedEntry setInNewsroom()  Sets the current record's "in_newsroom" value
 * @method FeedEntry setFeed()        Sets the current record's "Feed" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeedEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('feed_entry');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('feed_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('link', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('long_link', 'string', 512, array(
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('added_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('epoch_time', 'float', null, array(
             'type' => 'float',
             'length' => '',
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('in_newsroom', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Feed', array(
             'local' => 'feed_id',
             'foreign' => 'id'));
    }
}