<?php

/**
 * BaseVideoAd
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $code
 * @property string $internal_url
 * @property boolean $is_javascript
 * @property integer $push
 * 
 * @method integer getId()            Returns the current record's "id" value
 * @method string  getTitle()         Returns the current record's "title" value
 * @method string  getCode()          Returns the current record's "code" value
 * @method string  getInternalUrl()   Returns the current record's "internal_url" value
 * @method boolean getIsJavascript()  Returns the current record's "is_javascript" value
 * @method integer getPush()          Returns the current record's "push" value
 * @method VideoAd setId()            Sets the current record's "id" value
 * @method VideoAd setTitle()         Sets the current record's "title" value
 * @method VideoAd setCode()          Sets the current record's "code" value
 * @method VideoAd setInternalUrl()   Sets the current record's "internal_url" value
 * @method VideoAd setIsJavascript()  Sets the current record's "is_javascript" value
 * @method VideoAd setPush()          Sets the current record's "push" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVideoAd extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('video_ad');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('code', 'string', 1000000, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 1000000,
             ));
        $this->hasColumn('internal_url', 'string', 128, array(
             'notnull' => true,
             'type' => 'string',
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('is_javascript', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('push', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => 1,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $yiggsoftdelete0 = new yiggSoftDelete();
        $yiggdescription0 = new yiggDescription();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'length' => 128,
             'name' => 'internal_url',
             ));
        $this->actAs($timestampable0);
        $this->actAs($yiggsoftdelete0);
        $this->actAs($yiggdescription0);
        $this->actAs($sluggable0);
    }
}