<?php

/**
 * BaseUserOnlineLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property User $User
 * 
 * @method integer       getId()      Returns the current record's "id" value
 * @method integer       getUserId()  Returns the current record's "user_id" value
 * @method User          getUser()    Returns the current record's "User" value
 * @method UserOnlineLog setId()      Sets the current record's "id" value
 * @method UserOnlineLog setUserId()  Sets the current record's "user_id" value
 * @method UserOnlineLog setUser()    Sets the current record's "User" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserOnlineLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_online_log');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}