<?php

/**
 * BaseWspyTweet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $twitter_id
 * @property string $text
 * @property string $source
 * @property string $username
 * @property string $link
 * @property string $profile_image
 * @property timestamp $created_at
 * @property string $language
 * 
 * @method integer   getId()            Returns the current record's "id" value
 * @method integer   getTwitterId()     Returns the current record's "twitter_id" value
 * @method string    getText()          Returns the current record's "text" value
 * @method string    getSource()        Returns the current record's "source" value
 * @method string    getUsername()      Returns the current record's "username" value
 * @method string    getLink()          Returns the current record's "link" value
 * @method string    getProfileImage()  Returns the current record's "profile_image" value
 * @method timestamp getCreatedAt()     Returns the current record's "created_at" value
 * @method string    getLanguage()      Returns the current record's "language" value
 * @method WspyTweet setId()            Sets the current record's "id" value
 * @method WspyTweet setTwitterId()     Sets the current record's "twitter_id" value
 * @method WspyTweet setText()          Sets the current record's "text" value
 * @method WspyTweet setSource()        Sets the current record's "source" value
 * @method WspyTweet setUsername()      Sets the current record's "username" value
 * @method WspyTweet setLink()          Sets the current record's "link" value
 * @method WspyTweet setProfileImage()  Sets the current record's "profile_image" value
 * @method WspyTweet setCreatedAt()     Sets the current record's "created_at" value
 * @method WspyTweet setLanguage()      Sets the current record's "language" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWspyTweet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wspy_tweet');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('twitter_id', 'integer', 20, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('text', 'string', 255, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('source', 'string', 512, array(
             'notnull' => false,
             'type' => 'string',
             'length' => 512,
             ));
        $this->hasColumn('username', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('link', 'string', 512, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 512,
             ));
        $this->hasColumn('profile_image', 'string', 512, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 512,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('language', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}