<?php

/**
 * BaseFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $file_directory
 * @property string $file_name
 * @property string $file_type
 * @property User $User
 * @property Doctrine_Collection $Sponsoring
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getFileDirectory()  Returns the current record's "file_directory" value
 * @method string              getFileName()       Returns the current record's "file_name" value
 * @method string              getFileType()       Returns the current record's "file_type" value
 * @method User                getUser()           Returns the current record's "User" value
 * @method Doctrine_Collection getSponsoring()     Returns the current record's "Sponsoring" collection
 * @method File                setId()             Sets the current record's "id" value
 * @method File                setFileDirectory()  Sets the current record's "file_directory" value
 * @method File                setFileName()       Sets the current record's "file_name" value
 * @method File                setFileType()       Sets the current record's "file_type" value
 * @method File                setUser()           Sets the current record's "User" value
 * @method File                setSponsoring()     Sets the current record's "Sponsoring" collection
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('file_directory', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file_type', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'id',
             'foreign' => 'avatar_id'));

        $this->hasMany('Sponsoring', array(
             'local' => 'id',
             'foreign' => 'image_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}