<?php

/**
 * BaseNotificationMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $sender_id
 * @property integer $recipient_id
 * @property enum $type
 * @property string $description
 * @property enum $status
 * @property string $ref_object_type
 * @property integer $ref_object_id
 * @property timestamp $read_at
 * @property User $Sender
 * @property User $Recipient
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getSenderId()        Returns the current record's "sender_id" value
 * @method integer             getRecipientId()     Returns the current record's "recipient_id" value
 * @method enum                getType()            Returns the current record's "type" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method enum                getStatus()          Returns the current record's "status" value
 * @method string              getRefObjectType()   Returns the current record's "ref_object_type" value
 * @method integer             getRefObjectId()     Returns the current record's "ref_object_id" value
 * @method timestamp           getReadAt()          Returns the current record's "read_at" value
 * @method User                getSender()          Returns the current record's "Sender" value
 * @method User                getRecipient()       Returns the current record's "Recipient" value
 * @method NotificationMessage setId()              Sets the current record's "id" value
 * @method NotificationMessage setSenderId()        Sets the current record's "sender_id" value
 * @method NotificationMessage setRecipientId()     Sets the current record's "recipient_id" value
 * @method NotificationMessage setType()            Sets the current record's "type" value
 * @method NotificationMessage setDescription()     Sets the current record's "description" value
 * @method NotificationMessage setStatus()          Sets the current record's "status" value
 * @method NotificationMessage setRefObjectType()   Sets the current record's "ref_object_type" value
 * @method NotificationMessage setRefObjectId()     Sets the current record's "ref_object_id" value
 * @method NotificationMessage setReadAt()          Sets the current record's "read_at" value
 * @method NotificationMessage setSender()          Sets the current record's "Sender" value
 * @method NotificationMessage setRecipient()       Sets the current record's "Recipient" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotificationMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notification_message');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('sender_id', 'integer', 11, array(
             'notnull' => true,
             'type' => 'integer',
             'default' => 1,
             'length' => 11,
             ));
        $this->hasColumn('recipient_id', 'integer', 11, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'email',
              1 => 'twitter_dm',
              2 => 'twitter',
              3 => 'web',
              4 => 'web_pers',
             ),
             ));
        $this->hasColumn('text as description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'send',
              1 => 'new',
              2 => 'failed',
              3 => 'retry',
             ),
             'default' => 'new',
             ));
        $this->hasColumn('ref_object_type', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('ref_object_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('read_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User as Sender', array(
             'local' => 'sender_id',
             'foreign' => 'id'));

        $this->hasOne('User as Recipient', array(
             'local' => 'recipient_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $yiggdescription0 = new yiggDescription(array(
             ));
        $yiggnotifcation0 = new yiggNotifcation(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($yiggdescription0);
        $this->actAs($yiggnotifcation0);
    }
}