<?php

/**
 * BaseStoryIndex
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $external_url
 * @property string $description
 * 
 * @method integer    getId()           Returns the current record's "id" value
 * @method string     getTitle()        Returns the current record's "title" value
 * @method string     getExternalUrl()  Returns the current record's "external_url" value
 * @method string     getDescription()  Returns the current record's "description" value
 * @method StoryIndex setId()           Sets the current record's "id" value
 * @method StoryIndex setTitle()        Sets the current record's "title" value
 * @method StoryIndex setExternalUrl()  Sets the current record's "external_url" value
 * @method StoryIndex setDescription()  Sets the current record's "description" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoryIndex extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story_index');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('title', 'string', 128, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('external_url', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('description', 'string', 1000000, array(
             'notnull' => true,
             'type' => 'string',
             'length' => 1000000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}