<?php

/**
 * BaseUserTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $tag_id
 * 
 * @method integer getId()      Returns the current record's "id" value
 * @method integer getUserId()  Returns the current record's "user_id" value
 * @method integer getTagId()   Returns the current record's "tag_id" value
 * @method UserTag setId()      Sets the current record's "id" value
 * @method UserTag setUserId()  Sets the current record's "user_id" value
 * @method UserTag setTagId()   Sets the current record's "tag_id" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_tag');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('tag_id', 'integer', 11, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 11,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}