<?php

/**
 * BaseUserDomainSubscription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $domain_id
 * @property User $User
 * @property Domain $Domain
 * 
 * @method integer                getUserId()    Returns the current record's "user_id" value
 * @method integer                getDomainId()  Returns the current record's "domain_id" value
 * @method User                   getUser()      Returns the current record's "User" value
 * @method Domain                 getDomain()    Returns the current record's "Domain" value
 * @method UserDomainSubscription setUserId()    Sets the current record's "user_id" value
 * @method UserDomainSubscription setDomainId()  Sets the current record's "domain_id" value
 * @method UserDomainSubscription setUser()      Sets the current record's "User" value
 * @method UserDomainSubscription setDomain()    Sets the current record's "Domain" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserDomainSubscription extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_domain_subscription');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('domain_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Domain', array(
             'local' => 'domain_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}