<?php

/**
 * BaseRedirect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $url
 * @property string $redirect_key
 * @property string $title
 * @property string $description
 * @property Doctrine_Collection $StoryRedirect
 * @property Doctrine_Collection $RedirectLog
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getUrl()           Returns the current record's "url" value
 * @method string              getRedirectKey()   Returns the current record's "redirect_key" value
 * @method string              getTitle()         Returns the current record's "title" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method Doctrine_Collection getStoryRedirect() Returns the current record's "StoryRedirect" collection
 * @method Doctrine_Collection getRedirectLog()   Returns the current record's "RedirectLog" collection
 * @method Redirect            setId()            Sets the current record's "id" value
 * @method Redirect            setUrl()           Sets the current record's "url" value
 * @method Redirect            setRedirectKey()   Sets the current record's "redirect_key" value
 * @method Redirect            setTitle()         Sets the current record's "title" value
 * @method Redirect            setDescription()   Sets the current record's "description" value
 * @method Redirect            setStoryRedirect() Sets the current record's "StoryRedirect" collection
 * @method Redirect            setRedirectLog()   Sets the current record's "RedirectLog" collection
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRedirect extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('redirect');
        $this->hasColumn('id', 'integer', 20, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('url', 'string', 512, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 512,
             ));
        $this->hasColumn('redirect_key', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 128,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StoryRedirect', array(
             'local' => 'id',
             'foreign' => 'redirect_id'));

        $this->hasMany('RedirectLog', array(
             'local' => 'id',
             'foreign' => 'redirect_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}