<?php

/**
 * BaseUserPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $permission_level
 * @property User $User
 * 
 * @method integer        getId()               Returns the current record's "id" value
 * @method integer        getUserId()           Returns the current record's "user_id" value
 * @method integer        getPermissionLevel()  Returns the current record's "permission_level" value
 * @method User           getUser()             Returns the current record's "User" value
 * @method UserPermission setId()               Sets the current record's "id" value
 * @method UserPermission setUserId()           Sets the current record's "user_id" value
 * @method UserPermission setPermissionLevel()  Sets the current record's "permission_level" value
 * @method UserPermission setUser()             Sets the current record's "User" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_permission');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('permission_level', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('permissions', array(
             'fields' => 'permission_level',
             ));
        $this->index('permission_user', array(
             'fields' => 'user_id',
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}