<?php

/**
 * BaseRedirectLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $redirect_id
 * @property string $language
 * @property string $user_agent
 * @property string $referer
 * @property integer $ip_crc32
 * @property Redirect $Redirect
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getRedirectId()  Returns the current record's "redirect_id" value
 * @method string      getLanguage()    Returns the current record's "language" value
 * @method string      getUserAgent()   Returns the current record's "user_agent" value
 * @method string      getReferer()     Returns the current record's "referer" value
 * @method integer     getIpCrc32()     Returns the current record's "ip_crc32" value
 * @method Redirect    getRedirect()    Returns the current record's "Redirect" value
 * @method RedirectLog setId()          Sets the current record's "id" value
 * @method RedirectLog setRedirectId()  Sets the current record's "redirect_id" value
 * @method RedirectLog setLanguage()    Sets the current record's "language" value
 * @method RedirectLog setUserAgent()   Sets the current record's "user_agent" value
 * @method RedirectLog setReferer()     Sets the current record's "referer" value
 * @method RedirectLog setIpCrc32()     Sets the current record's "ip_crc32" value
 * @method RedirectLog setRedirect()    Sets the current record's "Redirect" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRedirectLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('redirect_log');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('redirect_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('language', 'string', 12, array(
             'type' => 'string',
             'length' => 12,
             ));
        $this->hasColumn('user_agent', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('referer', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ip_crc32', 'integer', null, array(
             'type' => 'integer',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Redirect', array(
             'local' => 'redirect_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}