<?php

/**
 * BaseSponsoring
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $deal_id
 * @property integer $place_id
 * @property integer $invitation_user_id
 * @property integer $image_id
 * @property string $image_title
 * @property string $sponsor_url
 * @property boolean $payed
 * @property integer $clicks
 * @property integer $impressions
 * @property boolean $status
 * @property timestamp $expires
 * @property Deal $Deal
 * @property SponsoringPlace $SponsoringPlace
 * @property User $InvitationUser
 * @property File $Image
 * 
 * @method integer         getId()                 Returns the current record's "id" value
 * @method integer         getDealId()             Returns the current record's "deal_id" value
 * @method integer         getPlaceId()            Returns the current record's "place_id" value
 * @method integer         getInvitationUserId()   Returns the current record's "invitation_user_id" value
 * @method integer         getImageId()            Returns the current record's "image_id" value
 * @method string          getImageTitle()         Returns the current record's "image_title" value
 * @method string          getSponsorUrl()         Returns the current record's "sponsor_url" value
 * @method boolean         getPayed()              Returns the current record's "payed" value
 * @method integer         getClicks()             Returns the current record's "clicks" value
 * @method integer         getImpressions()        Returns the current record's "impressions" value
 * @method boolean         getStatus()             Returns the current record's "status" value
 * @method timestamp       getExpires()            Returns the current record's "expires" value
 * @method Deal            getDeal()               Returns the current record's "Deal" value
 * @method SponsoringPlace getSponsoringPlace()    Returns the current record's "SponsoringPlace" value
 * @method User            getInvitationUser()     Returns the current record's "InvitationUser" value
 * @method File            getImage()              Returns the current record's "Image" value
 * @method Sponsoring      setId()                 Sets the current record's "id" value
 * @method Sponsoring      setDealId()             Sets the current record's "deal_id" value
 * @method Sponsoring      setPlaceId()            Sets the current record's "place_id" value
 * @method Sponsoring      setInvitationUserId()   Sets the current record's "invitation_user_id" value
 * @method Sponsoring      setImageId()            Sets the current record's "image_id" value
 * @method Sponsoring      setImageTitle()         Sets the current record's "image_title" value
 * @method Sponsoring      setSponsorUrl()         Sets the current record's "sponsor_url" value
 * @method Sponsoring      setPayed()              Sets the current record's "payed" value
 * @method Sponsoring      setClicks()             Sets the current record's "clicks" value
 * @method Sponsoring      setImpressions()        Sets the current record's "impressions" value
 * @method Sponsoring      setStatus()             Sets the current record's "status" value
 * @method Sponsoring      setExpires()            Sets the current record's "expires" value
 * @method Sponsoring      setDeal()               Sets the current record's "Deal" value
 * @method Sponsoring      setSponsoringPlace()    Sets the current record's "SponsoringPlace" value
 * @method Sponsoring      setInvitationUser()     Sets the current record's "InvitationUser" value
 * @method Sponsoring      setImage()              Sets the current record's "Image" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSponsoring extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sponsoring');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('deal_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('place_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('invitation_user_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 11,
             ));
        $this->hasColumn('image_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('image_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sponsor_url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('payed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('clicks', 'integer', 11, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 11,
             ));
        $this->hasColumn('impressions', 'integer', 11, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 11,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('expires', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Deal', array(
             'local' => 'deal_id',
             'foreign' => 'id'));

        $this->hasOne('SponsoringPlace', array(
             'local' => 'place_id',
             'foreign' => 'id'));

        $this->hasOne('User as InvitationUser', array(
             'local' => 'invitation_user_id',
             'foreign' => 'id'));

        $this->hasOne('File as Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}