<?php

/**
 * BaseStoryTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $story_id
 * @property integer $tag_id
 * 
 * @method integer  getId()       Returns the current record's "id" value
 * @method integer  getStoryId()  Returns the current record's "story_id" value
 * @method integer  getTagId()    Returns the current record's "tag_id" value
 * @method StoryTag setId()       Sets the current record's "id" value
 * @method StoryTag setStoryId()  Sets the current record's "story_id" value
 * @method StoryTag setTagId()    Sets the current record's "tag_id" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoryTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story_tag');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('story_id', 'integer', 11, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('tag_id', 'integer', 11, array(
             'notnull' => true,
             'type' => 'integer',
             'length' => 11,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}