<?php

/**
 * BaseStoryFilterOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Stories
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getStories() Returns the current record's "Stories" collection
 * @method Tag                 setId()      Sets the current record's "id" value
 * @method Tag                 setName()    Sets the current record's "name" value
 * @method Tag                 setStories() Sets the current record's "Stories" collection
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoryFilterOption extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story_filter_option');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('name', 'string', 20, array(
             'notnull' => false,
             'type' => 'string',
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('value', 'integer', 11, array(
             'notnull' => false,
             'type' => 'integer',
             'length' => 11,
             ));
        
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }   
}