<?php

/**
 * BaseDeal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $sponsoring_id
 * @property float $credit
 * @property float $debit
 * @property boolean $payed
 * @property integer $sponsor_deal_id
 * @property string $buyer_first_name
 * @property string $buyer_last_name
 * @property string $buyer_street1
 * @property string $buyer_street2
 * @property string $buyer_city
 * @property string $buyer_state
 * @property string $buyer_zip
 * @property string $buyer_country
 * @property string $buyer_email
 * @property User $User
 * @property Sponsoring $Sponsoring
 * @property Deal $SponsorDeal
 * @property Doctrine_Collection $Deal
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getUserId()           Returns the current record's "user_id" value
 * @method integer             getSponsoringId()     Returns the current record's "sponsoring_id" value
 * @method float               getCredit()           Returns the current record's "credit" value
 * @method float               getDebit()            Returns the current record's "debit" value
 * @method boolean             getPayed()            Returns the current record's "payed" value
 * @method integer             getSponsorDealId()    Returns the current record's "sponsor_deal_id" value
 * @method string              getBuyerFirstName()   Returns the current record's "buyer_first_name" value
 * @method string              getBuyerLastName()    Returns the current record's "buyer_last_name" value
 * @method string              getBuyerStreet1()     Returns the current record's "buyer_street1" value
 * @method string              getBuyerStreet2()     Returns the current record's "buyer_street2" value
 * @method string              getBuyerCity()        Returns the current record's "buyer_city" value
 * @method string              getBuyerState()       Returns the current record's "buyer_state" value
 * @method string              getBuyerZip()         Returns the current record's "buyer_zip" value
 * @method string              getBuyerCountry()     Returns the current record's "buyer_country" value
 * @method string              getBuyerEmail()       Returns the current record's "buyer_email" value
 * @method User                getUser()             Returns the current record's "User" value
 * @method Sponsoring          getSponsoring()       Returns the current record's "Sponsoring" value
 * @method Deal                getSponsorDeal()      Returns the current record's "SponsorDeal" value
 * @method Doctrine_Collection getDeal()             Returns the current record's "Deal" collection
 * @method Deal                setId()               Sets the current record's "id" value
 * @method Deal                setUserId()           Sets the current record's "user_id" value
 * @method Deal                setSponsoringId()     Sets the current record's "sponsoring_id" value
 * @method Deal                setCredit()           Sets the current record's "credit" value
 * @method Deal                setDebit()            Sets the current record's "debit" value
 * @method Deal                setPayed()            Sets the current record's "payed" value
 * @method Deal                setSponsorDealId()    Sets the current record's "sponsor_deal_id" value
 * @method Deal                setBuyerFirstName()   Sets the current record's "buyer_first_name" value
 * @method Deal                setBuyerLastName()    Sets the current record's "buyer_last_name" value
 * @method Deal                setBuyerStreet1()     Sets the current record's "buyer_street1" value
 * @method Deal                setBuyerStreet2()     Sets the current record's "buyer_street2" value
 * @method Deal                setBuyerCity()        Sets the current record's "buyer_city" value
 * @method Deal                setBuyerState()       Sets the current record's "buyer_state" value
 * @method Deal                setBuyerZip()         Sets the current record's "buyer_zip" value
 * @method Deal                setBuyerCountry()     Sets the current record's "buyer_country" value
 * @method Deal                setBuyerEmail()       Sets the current record's "buyer_email" value
 * @method Deal                setUser()             Sets the current record's "User" value
 * @method Deal                setSponsoring()       Sets the current record's "Sponsoring" value
 * @method Deal                setSponsorDeal()      Sets the current record's "SponsorDeal" value
 * @method Deal                setDeal()             Sets the current record's "Deal" collection
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('deal');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('sponsoring_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 11,
             ));
        $this->hasColumn('credit', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
        $this->hasColumn('debit', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
        $this->hasColumn('payed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('sponsor_deal_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 11,
             ));
        $this->hasColumn('buyer_first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('buyer_last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('buyer_street1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('buyer_street2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('buyer_city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('buyer_state', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('buyer_zip', 'string', 11, array(
             'type' => 'string',
             'length' => 11,
             ));
        $this->hasColumn('buyer_country', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('buyer_email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Sponsoring', array(
             'local' => 'sponsoring_id',
             'foreign' => 'id'));

        $this->hasOne('Deal as SponsorDeal', array(
             'local' => 'sponsor_deal_id',
             'foreign' => 'id'));

        $this->hasMany('Deal', array(
             'local' => 'id',
             'foreign' => 'sponsor_deal_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}