<?php

/**
 * BaseUserFollowing
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $following_id
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getUserId()       Returns the current record's "user_id" value
 * @method integer       getFollowingId()  Returns the current record's "following_id" value
 * @method UserFollowing setId()           Sets the current record's "id" value
 * @method UserFollowing setUserId()       Sets the current record's "user_id" value
 * @method UserFollowing setFollowingId()  Sets the current record's "following_id" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserFollowing extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_following');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('following_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('unique_idx', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'following_id',
             ),
             'type' => 'unique',
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $yiggnotifcation0 = new yiggNotifcation(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($yiggnotifcation0);
    }
}