<?php

/**
 * BaseStoryRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $story_id
 * @property integer $rating_id
 * @property integer $user_id
 * @property Rating $Rating
 * @property User $User
 * @property Story $Story
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method integer     getStoryId()   Returns the current record's "story_id" value
 * @method integer     getRatingId()  Returns the current record's "rating_id" value
 * @method integer     getUserId()    Returns the current record's "user_id" value
 * @method Rating      getRating()    Returns the current record's "Rating" value
 * @method User        getUser()      Returns the current record's "User" value
 * @method Story       getStory()     Returns the current record's "Story" value
 * @method StoryRating setId()        Sets the current record's "id" value
 * @method StoryRating setStoryId()   Sets the current record's "story_id" value
 * @method StoryRating setRatingId()  Sets the current record's "rating_id" value
 * @method StoryRating setUserId()    Sets the current record's "user_id" value
 * @method StoryRating setRating()    Sets the current record's "Rating" value
 * @method StoryRating setUser()      Sets the current record's "User" value
 * @method StoryRating setStory()     Sets the current record's "Story" value
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoryRating extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story_rating');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('story_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('rating_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));


        $this->index('story_rating_story', array(
             'fields' => 'story_id',
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Rating', array(
             'local' => 'rating_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Story', array(
             'local' => 'story_id',
             'foreign' => 'id'));
    }
}