<?php

/**
 * BaseSponsoringPlace
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $description
 * @property string $intern_url
 * @property integer $width
 * @property integer $height
 * @property float $price
 * @property integer $capacity
 * @property Doctrine_Collection $Invitation
 * @property Doctrine_Collection $Sponsoring
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getInternUrl()   Returns the current record's "intern_url" value
 * @method integer             getWidth()       Returns the current record's "width" value
 * @method integer             getHeight()      Returns the current record's "height" value
 * @method float               getPrice()       Returns the current record's "price" value
 * @method integer             getCapacity()    Returns the current record's "capacity" value
 * @method Doctrine_Collection getInvitation()  Returns the current record's "Invitation" collection
 * @method Doctrine_Collection getSponsoring()  Returns the current record's "Sponsoring" collection
 * @method SponsoringPlace     setId()          Sets the current record's "id" value
 * @method SponsoringPlace     setDescription() Sets the current record's "description" value
 * @method SponsoringPlace     setInternUrl()   Sets the current record's "intern_url" value
 * @method SponsoringPlace     setWidth()       Sets the current record's "width" value
 * @method SponsoringPlace     setHeight()      Sets the current record's "height" value
 * @method SponsoringPlace     setPrice()       Sets the current record's "price" value
 * @method SponsoringPlace     setCapacity()    Sets the current record's "capacity" value
 * @method SponsoringPlace     setInvitation()  Sets the current record's "Invitation" collection
 * @method SponsoringPlace     setSponsoring()  Sets the current record's "Sponsoring" collection
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSponsoringPlace extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sponsoring_place');
        $this->hasColumn('id', 'integer', 11, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('intern_url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('width', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('height', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('capacity', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Invitation', array(
             'local' => 'id',
             'foreign' => 'place_id'));

        $this->hasMany('Sponsoring', array(
             'local' => 'id',
             'foreign' => 'place_id'));
    }
}