<?php

/**
 * AuthNonceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthNonceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuthNonceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AuthNonce');
    }
}