<?php

/**
 * AuthToken
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AuthToken extends BaseAuthToken {
  /**
   * check id token is authorized
   *
   * @return boolean
   */
  public function isAuthorized() {
    if ($this->getUserId()) {
      return true;
    } else {
      return false;
    }
  }

  /**
   * get the community to a token
   *
   * @return Community
   */
  public function getConsumer() {
    return Doctrine::getTable("AuthConsumer")->findOneByConsumerKey($this->getConsumerKey());
  }
}
