<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthUserKey extends BaseAuthUserKey
{
  public function preInsert($event)
  {
    $this->user_key = md5( rand(100000, time()));
    $this->created_at = yiggTools::getDbDate(null,time());
  }
}