<?php

/**
 * AuthTokenTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthTokenTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object AuthTokenTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('AuthToken');
  }

  public function deleteExpired() {
    $this->getQueryObject()
         ->delete()
         ->where("created_at <= ? ", "DATE_SUB(NOW(), INTERVAL 10 MINUTE)")
         ->andWhere("token_type = ?", "request")
         ->execute();
  }

  public function lookup($consumer, $token_type, $token) {
    $object = $this->getQueryObject()
         ->select('*')
         ->from("AuthToken")
         ->where("token_key = ?", $token)
         ->andWhere("token_type = ?", $token_type);

    if ($consumer) {
      $object->andWhere('consumer_key = ?', $consumer->key);
    }

    return $object->fetchOne();
  }
}