<?php

/**
 * AuthConsumerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthConsumerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuthConsumerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AuthConsumer');
    }
}