<?php

/**
 * AuthNonceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthNonceTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object AuthNonceTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('AuthNonce');
  }

  public function deleteExpired() {
    $this->getQueryObject()->delete()->where("created_at <= ?", "DATE_SUB(NOW(), INTERVAL 60 MINUTE)")->execute();
  }

  public function hasBeenUsed($consumer, $token, $nonce) {
    $nonce = $this->getQueryObject()
         ->select('*')
         ->from("AuthNonce")
         ->where('consumer_key = ?', $consumer->key)
         ->andWhere("nonce = ?", $nonce);

    // check token
    if ($token) {
      $nonce->andWhere("token_key = ?", $token->key);
    }

    return $nonce->fetchOne();
  }
}