<?php

/**
 * BlacklistTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlacklistTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object BlacklistTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Blacklist');
    }

    public function getBlacklistAsArray() {
      $bad_words = Doctrine::getTable("Blacklist")
         ->getQueryObject()
         ->select("word")->from("Blacklist INDEXBY word")
         ->execute(array(),Doctrine::HYDRATE_ARRAY);

      if ($bad_words) {
        return array_keys($bad_words);
      } else {
        return array();
      }
    }
}