<?php

/**
 * DomainStatsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DomainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DomainStatsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Domain');
    }

    /**
     * Checks to see if the url in question (full url) has been white / blacklistsed
     * @param $url the url in question
     * @param $status string whitelist / blacklist
     * @return Boolean
     */
    public function hasStatus($url, $status)
    {
      $parsed_url = parse_url($url);
      return (
          $this->getQueryObject()
          ->select('id')
          ->from("Domain")
          ->where('hostname = ?', $parsed_url['host'])
          ->addWhere("domain_status = ?", $status)
          ->count() > 0) ? true : false;
    }
}