<?php

/**
 * Feed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
class Feed extends BaseFeed
{
}
