<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class History extends BaseHistory
{
  /**
   * Send notifications about this the new Follower to the Followed user
   */
  public function processNotifications()
  {
    return;
    $conn = Doctrine::getConnectionByTableName("User");
    $user = Doctrine::getTable("User")->findOneById($this->Story->user_id);
    $user->notify(
      $this,
      "NewHistory",
      true,
      $conn
    );
  }
}