<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Invitation extends BaseInvitation
{
  public function __toString()
  {
    $user = Doctrine::getTable('User')->find($this->user_id);
    return $this->id.' - '.$this->email.' [by '.$user['username'].']';
  }

  public static function create( $values )
  {
    $invitation = new self();
    $invitation->fromArray( $values );
    $invitation->save();
    return $invitation;
  }

  /**
   * try to guess name of an User being invited
   * refactored to use query instead of iterating through
   * every invitation.
   * @todo should probably be on the table not this object.
   */
  public static function guessName($deal)
  {
    $invitation = Doctrine::getTable('Invitation')->findByDql('email = %s',array($deal->User->Email));
    if( count($invitation) > 0)
    {
      return $invitation[0]->name;
    }
    return $deal->User->username;
  }
}
