<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificationMessage extends BaseNotificationMessage
{
  private $ref_object = null;

  /**
   * This returns the referenced object.
   * Note: it will not however guarentee the objects refrences
   * are correct and valid.
   *
   * @return Doctrine_Object
   */
  public function getReferencedObject()
  {
    if( null === $this->ref_object && class_exists($this->ref_object_type))
    {
      $table = Doctrine::getTable($this->ref_object_type);
      $this->ref_object = $table->findOneById($this->ref_object_id);

      return $this->ref_object;
    }
    return $this->ref_object;
  }

  public function isRecipient( $user )
  {
    if(!$user instanceof User)
    {
      throw new InvalidArgumentException('recipeint is not of type User');
    }

    return ($this->recipient_id === $user->id);
  }

  public function isRead()
  {
    return (false === empty($this->read_at));
  }

  public function getTaskLink($task)
  {
    return "@notification_tasks?task=$task&id=".$this->id;
  }

  public function processNotifications()
  {
    if($this->ref_object_type !== "NotificationMessage")
    {
      return;
    }
    $conn = Doctrine::getConnectionByTableName("NotificationMessage");

    $this->Recipient->notify(
      $this,
      "NotificationMessage",
      false,
      $conn
    );
  }
}