<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoryComment extends BaseStoryComment
{
  public function getParent()
  {
    return $this->Story;
  }

  public function getContext()
  {
    return $this->Comment;
  }

  public function processNotifications()
  {
    return $this->Comment->processNotifications($this);
  }
}