<?php

/**
 * StoryIndexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoryIndexTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StoryIndexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StoryIndex');
    }
}