<?php

/**
 * TwitterSearchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TwitterSearchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TwitterSearchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TwitterSearch');
    }
}