<?php

/**
 * UserDomainSubscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserDomainSubscriptionTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object UserDomainSubscriptionTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('UserDomainSubscription');
  }

  public static function getSubscriberQuery($user_id, $domain_id)
  {
    return self::getInstance()->getQueryObject()
                              ->where("user_id = ?", $user_id)
                              ->addWhere("domain_id = ?", $domain_id);
  }
}