<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserStats extends BaseUserStats
{
  private $rank_map = array (
    'Neuhamster', 'Fauler Hamster', 'Zwerghamster', 'Streifenhamster', 'Feldhamster', 'Mittelhamster', 'Schneller Hamster', 'Fleissiger Hamster', 'Grosshamster', 'Goldhamster'
  );

  public function updateStats()
  {
    $this->storys_total = Doctrine_Query::create()
                          ->from("Story")
                          ->where("user_id = ?", $this->user_id)
                          ->count();

    $this->comments_total = Doctrine_Query::create()
                          ->from("Comment")
                          ->where("user_id = ?", $this->user_id)
                          ->count();

    $this->friends_total = Doctrine_Query::create()
                          ->from("UserFollowing")
                          ->where("user_id = ?", $this->user_id)
                          ->count();

    $this->external_friends_total = Doctrine_Query::create()
                          ->from("UserFollowing")
                          ->where("following_id = ?", $this->user_id)
                          ->count();


    $this->external_comments_total = Doctrine_Query::create()
                          ->from("Story s")
                          ->leftJoin("s.Comments c")
                          ->where("s.user_id = ?", $this->user_id)
                          ->count();

    $this->external_yiggs_total = Doctrine_Query::create()
                          ->select("COUNT(r.id) as num_rows")
                          ->from("Story s")
                          ->leftJoin("s.Ratings r")
                          ->where("s.user_id = ?", $this->user_id)
                          ->fetchOne()
                          ->num_rows;

    $this->yiggs_total = Doctrine_Query::create()
                          ->from("StoryRating")
                          ->where("user_id = ?", $this->user_id)
                          ->count();


    $this->storys_total = Doctrine_Query::create()
                          ->from("Story")
                          ->where("user_id = ?", $this->user_id)
                          ->count();

    $this->story_renders_total = Doctrine_Query::create()
                          ->from("StoryRender")
                          ->where("user_id = ?", $this->user_id)
                          ->count();

    $this->last_calculated = yiggTools::getDbDate ();
    $this->save();
  }


  function updateCommentAward()
  {
    if ($this->comments_total < 80)
    {
      $this->comment_award = 0;
    }
    else if ($this->comments_total < 250)
    {
      $this->comment_award = 1;
    }
    else if ($this->comments_total < 500)
    {
      $this->comment_award = 2;
    }
    else if ($this->comments_total < 1000)
    {
      $this->comment_award = 3;
    }
    else if ($this->comments_total >= 1000)
    {
      $this->comment_award = 4;
    }
  }

  private function updateRank()
  {
    if ($this->yipps > 131072)
    {
      $this->rank = 9;
    }
    else if ($this->yipps > 65536)
    {
      $this->rank = 8;
    }
    else if ($this->yipps > 16384)
    {
      $this->rank = 7;
    }
    else if ($this->yipps > 4096)
    {
      $this->rank = 6;
    }
    else if ($this->yipps > 1024)
    {
      $this->rank = 5;
    }
    else if ($this->yipps > 256)
    {
      $this->rank = 4;
    }
    else if ($this->yipps > 64)
    {
      $this->rank = 3;
    }
    else if ($this->yipps > 16)
    {
      $this->rank = 2;
    }
    else if ($this->yipps > 4)
    {
      $this->rank = 1;
    }
    else
    {
      $this->rank = 0;
    }
  }

  function updateReadAward()
  {
    if ($this->story_renders_total < 800)
    {
      $this->reading_award = 0;
    }
    else if ($this->story_renders_total < 8000)
    {
      $this->reading_award = 1;
    }
    else if ($this->story_renders_total < 16000)
    {
      $this->reading_award = 2;
    }
    else if ($this->story_renders_total < 64000)
    {
      $this->reading_award = 3;
    }
    else if ($this->story_renders_total >= 64000)
    {
      $this->reading_award = 4;
    }
  }

  /**
   *
   * @return integer YiPPs
   */
  public function calculateYipps()
  {
    $YiPPs = 0;
    $YiPPs += 3 * $this->storys_total;
    $YiPPs += 0.5 * $this->external_yiggs_total;
    $YiPPs += 5 * $this->external_friends_total;
    $YiPPs += 1 * $this->friends_total;
    $YiPPs += 2 * $this->comments_total;

    return $YiPPs;
  }

  /**
   * Get name of userrank
   * @return string Userrank
   */
  function getUserRank()
  {
    return empty ( $this->rank ) ? $this->rank_map [0] : $this->rank_map [$this->rank];
  }

  public function preValidate($event)
  {
    if($this->state() === Doctrine_Record::STATE_TDIRTY) // Do nothing if record just got created (eg on creation of a user)
    {
      return;
    }
    $this->yipps = (integer)$this->calculateYipps();
    $this->updateRank ();
    $this->updateReadAward ();
    $this->updateCommentAward ();
  }
}