<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTagTable extends Doctrine_Table
{

  /**
   * returns tags related to the user_id
   *
   * @param int Userid
   * @return UserTags
   */
  public static function getTags($user_id)
  {
    $query = Doctrine_Query::create()
      ->select('u.id, t.*')
      ->from('Tag t INDEXBY t.id')
      ->innerJoin('t.Users u')
      ->where('u.id = ?', $user_id);
    return $query->execute();
  }
}