<?php

/**
 * UserOnlineLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserOnlineLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserOnlineLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserOnlineLog');
    }
}