<?php

/**
 * VideoAd
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    yigg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class VideoAd extends BaseVideoAd
{
  private $cache;

  public function construct()
  {
    $this->cache = new sfParameterHolder();
  }

  public function getCode()
  {
    return $this->getSizedCode();
  }

  public function getSizedCode($width = '400',$height ='300')
  {
    $code = $this->_get("code");
    $code = str_replace("%width%", $width, $code);
    $code = str_replace("%height%", $height, $code);
    $code = str_replace("&","&amp;",$code);
    return $code;
  }

  /**
   * Used by the email recommend form.
   * @return String
   */
  public function getLink()
  {
    return "@video_actions?action=show&id=" . $this['internal_url'];
  }



}
