prod:
  .settings:
    error_reporting:        <?php echo (E_PARSE | E_COMPILE_ERROR | E_ERROR | E_CORE_ERROR | E_USER_ERROR)."\n" ?>
    no_script_name:         true
    web_debug:				false

cache:
  .settings:
    web_debug:              true
    cache:                  true
    no_script_name:         false

test:
  .settings:
    error_reporting:        <?php echo (E_PARSE | E_COMPILE_ERROR | E_ERROR | E_CORE_ERROR | E_USER_ERROR)."\n" ?>
    cache:                  false
    no_script_name:         true

dev:
  .settings:
    no_script_name:         true
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              false
    cache:                  false
    compressed:             false
    etag:                   false

staging:
  .settings:
    no_script_name:         true
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              false
    cache:                  false
    compressed:             false
    etag:                   false

soap:
  .settings:
    error_reporting:        <?php echo (E_PARSE | E_COMPILE_ERROR | E_ERROR | E_CORE_ERROR | E_USER_ERROR)."\n" ?>

all:
  .actions:
    check_lock:             true                  # Change this when making the site unavaliable.
    default_module:         story                 # Default module and action to be called when
    default_action:         bestStories           # A routing rule doesn't set it
    no_script_name:         true                    # Enable the front controller name in generated URLs
    error_404_module:       system                # To be called when a 404 error is raised
    error_404_action:       error404              # Or when the requested URL doesn't match any routes
    login_module:           user                  # To be called when a non-authenticated user
    login_action:           login                 # Tries to access a secure page
    secure_module:          system
    secure_action:          secure
    unavailable_module:     system                # To be called when a user requests a page
    unavailable_action:     unavailable           # From an application disabled via the available setting below
    module_disabled_module: system                # To be called when a user requests
    module_disabled_action: disabled              # A module disabled in the module.yml
    allowed_failed_logins:  3                     # The number (array syntax starting at zero) of failed attempts at logging in to allow
    max_email_lookups:      3                     #  he number of max lookups per IP. (detecting brute force.)
    do_not_reply:           no-reply@yigg.de      # Bounce Email
    automatic_email_name:   YiGG Email Hampster   # Bounce Email name

  .settings:
    logging_enabled:        true
    cache:                  true
    etag:                   true
    compressed:             true
    validation_error_prefix:    ' '
    validation_error_suffix:    ' '
    validation_error_class:     'error_message'
    validation_error_id_prefix: 'error_for_'
    charset:                utf-8                 # default encoding charset.
    default_culture:        de_DE                 # culture
    standard_helpers:       [Partial, Cache, JavaScript, Image, Yigg, WebSemantics]
    csrf_secret:            0bIg938HyIgG          # form handling secret and csrf-protection
    use_process_cache:      true                   # Enable symfony optimizations based on PHP accelerators. Set to off for tests or when you have enabled a PHP accelerator in your server but don't want symfony to use it internally.
    check_lock:             true                    # Enable the application lock system triggered by the clear-cache and disable tasks. Set to on to have all requests to disabled applications redirected to the $sf_symfony_data_dir/web/arrors/unavailable.php page.
    strip_comments:         true                    # Remove comments in core framework classes as defined in the core_compile.yml
    escaping_strategy: 		true
    escaping_method:   		ESC_ENTITIES
