---
# All smilies are replaced with grouping, many for use eg: "{(^| )(8-\))|(8\))(([ /!,])|$)}"
# quotes must be double escaped.  ':''-(' => outputs => :'-(

all:
  smilies:
    options:
      prefix:             '((^| )*|>|;)('
      suffix:             ')(([ \!,.\n\t])|$|<)'

    smilies:
      'cool.png':         '(\s8\-\))|(\s8\))'
      'cry.png':          '(\s:''\()|(\s:''\-\()'
      'embarrassed.png':  '(\s:\-\[)|(\s:\[)'
      'footinmouth.png':  '(\s\*footinmouth\*)'
      'frown.png':        '(\s:\-\()|(\s:\()'
      'innocent.png':     '(\sO:\-\))|(\sO:\))|(\s0:\-\))|(\s0:\))'
      'kiss.png':         '(\s:\-\*)|(\s:\*)'
      'laughing.png':     '(\s:D)|(\s:\-D)'
      'moneyinmouth.png': '(\s:\$)|(\s:\-\&)'
      'sealed.png':       '(\s:\-X)|(\s:X)|(\s:\-x)|(\s:x)'
      'smile.png':        '(\s:\-\))|(\s:\))'
      'suprised.png':     '(\s:\-O)|(\s:O)|(\s:\-o)|(\s:o)|(\s:\-0)|(\s:0)'
      'tongue.png':       '(\s:\-P)|(\s:P)|(\s:\-b)|(\s:b)|(\s:p)|(\s:\-p)'
      'undecided.png':    '(\s:\-\/)|(\s:\/)|(\s:\-\\)|(\s:\\)'
      'wink.png':         '(\s;\-\))|(\s;\))'
      'yell.png':         '(\s:@)|(\s:\-@)'
      'popcorn.gif':      '(\s\*popcorn\*)'
      'keks.gif':         '(\s\*keks\*)'
      'party.gif':        '(\s\*party\*)'
      'horse.gif':        '(\s\*horse\*)'
      'zeitung.gif':      '(\s\*zeitung\*)'
      'hammer.gif':       '(\s\*hammer\*)'
      'motzen.gif':       '(\s\*motzen\*)'
      'kotzen.gif':       '(\s\*kotzen\*)'
      'bomb.gif':         '(\s\*bomb\*)'
      'mail.gif':         '(\s\*mail\*)'
      'blink.gif':        '(\s\*blink\*)'
      'schocker.gif':     '(\s\*schocker\*)'
      'rolleyes.gif':     '(\s\*rolleyes\*)'
      'dance.gif':        '(\s\*dance\*)'
      'pirate.gif':       '(\s\*pirate\*)'
      'mrpotato.png':     '(\s\*mrpotato\*)'
      'atomic.png':       '(\s\*atomic\*)'
      'bug.png':          '(\s\*bug\*)'
      'sun.png':          '(\s\*sun\*)'
      'game.png':         '(\s\*game\*)'
      'coffee.png':       '(\s\*coffee\*)'
      'rofl.gif':         '(\s\*rofl\*)'
      'sad.gif':          '(\s\*sad\*)'
      'streber.gif':      '(\s\*streber\*)'
      'peace.gif':        '(\s\*peace\*)'
      'beten.gif':        '(\s\*prayer\*)'
      'beten.gif':        '(\s\*beten\*)'
      'beten.gif':        '(\s\*bow\*)'
      'git.gif':          '(\s\*rock\*)'
      'ranting.gif':      '(\s\*rant\*)'
      'marvin.gif':       '(\s\*marvin\*)'
      'alien.gif':        '(\s\*alien\*)'