spySuccess:
  metas:
    title:        YiGGspion - YiGG.de
    description:  Im YiGG-Spion erhälst du eine aktuelle Übersicht davon, was gerade auf YiGG passiert. Steig über die Links direkt ins Geschehen ein.
    keywords:     YiGG, Spion, Live, Community, Übersicht, Kommentare, Bewertungen