worldSpySuccess:
  metas:
    title:        Weltspion - YiGG.de
    description:  In unserem Weltspion kannst du sehen, was gerade in der Welt passiert, den er grasst tausende RSS-Feeds auf neue Ereignisse ab.
    keywords:     YiGG, Weltspion, Live, RSS, Nachrichten

topStoriesSuccess:
  metas:
    title:        Social Media Newsroom - YiGG.de
    description:  In unserem Social Media Newsroom siehst Du die interessantesten Nachrichten aus dem Weltspion.
    keywords:     YiGG, Weltspion, Live, RSS, Nachrichten