generator:
  class: sfDoctrineGenerator
  param:
    model_class:           VideoAd
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          video
    with_doctrine_route:   true
    actions_base_class:    sfActions
    config:
      actions: ~
      fields:
        title:
        code:
          help: Remember you MUST add the height "%height%" and width "%width%" elements to the code before saving!
        is_javascript:
      list:
        title:             VideoAd Verwaltung
        display:           [code, title, created_at]
        sort:              [created_at]
        max_per_page:      50
      new:


      filter:
        display:           [title]
      form:    ~
      edit:
        display:           [title, code, push]
      new:
        display:           [title, code, push]