prod:
  yigg:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=yigg-db1.cikaf9ikcmcc.eu-west-1.rds.amazonaws.com;port=3306;dbname=yigg_devel'
      username: yigg_devel
      password: dLdQGRPjhxAdbmWt
      attributes:
        use_dql_callbacks: true
        validate: true

staging:
  yigg:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=yigg_staging'
      username: ekaabo
      password: k9zhgt1u!
      attributes:
        use_dql_callbacks: true
        validate: true

dev:
  yigg:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=yigg_devel'
      username: yigg_devel
      password: k3ZrU=(GyedFmS[s%/3)yI8iYHq>*6
      attributes:
        use_dql_callbacks: true
        validate: true