yiggDailySuccess:
  metas:
    title:        Täglich die besten News von Yigg.de - YiGG Daily - YiGG.de
    keywords:     Podcast, Video, Social News, YiGG
    description:  YiGG Daily ist ein Podcast von YiGG-Benutzern für YiGG Benutzer. Hier gibt es werktäglich die besten Social-News Deutschlands.