Category:
  connection: yigg
  tableName: category
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Stories:
      class: Story
      refClass: StoryCategory
      foreignAlias: Category
  options:
    collate: utf8_unicode_ci
    charset: utf8

StoryCategory:
  connection: yigg
  tableName: story_category
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    story_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    category_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  options:
    collate: utf8_unicode_ci
    charset: utf8