---
NotificationMessage:
  actAs: [Timestampable, yiggDescription, yiggNotifcation]
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(11)
    sender_id:
      notnull: true
      type: integer(11)
      default: 1
    recipient_id:
      notnull: true
      type: integer(11)
    type:
      type: enum
      notnull: true
      values: ['email', 'twitter_dm', 'twitter', 'web', 'web_pers']
    text as description:
      type: string(4000)
    status:
      type: enum
      values: ['send', 'new', 'failed','retry']
      default: new
    ref_object_type:
      type: string(64)
    ref_object_id:
      type: integer(11)
    read_at:
      type: timestamp(25)
  options:
    collate: utf8_unicode_ci
    charset: utf8
  relations:
    Sender:
      class: User
      local: sender_id
      foreign: id
      type: one
    Recipient:
      class: User
      local: recipient_id
      foreign: id
      type: one