---
AuthToken:
  actAs: [Timestampable]
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer
    user_id:
      notnull: true
      type: integer
    consumer_key:       varchar(255)
    token_key:          varchar(255)
    token_secret:       varchar(255)
    token_type:         varchar(40)
    oauth_callback:     varchar(255)
    oauth_verifier:     varchar(40)
  relations:
    User:
      class: User
      local: user_id
      foreign: id
      type: one

AuthNonce:
  actAs: [Timestampable]
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer
    consumer_key:       varchar(255)
    token_key:          varchar(255)
    nonce:              text