---
AuthToken:
  actAs: [Timestampable]
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer
    user_id:
      type: integer
    consumer_key:       varchar(255)
    token_key:          varchar(255)
    token_secret:       varchar(255)
    token_type:         varchar(40)
    oauth_callback:     varchar(255)
    oauth_verifier:     varchar(40)

AuthNonce:
  actAs: [Timestampable]
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer
    consumer_key:       varchar(255)
    token_key:          varchar(255)
    nonce:              varchar

AuthConsumer:
  actAs: [Timestampable]
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer
    name:               varchar(255)
    description:        varchar(255)
    consumer_key:       varchar(255)
    consumer_secret:    varchar(255)
    consumer_callback:  varchar(255)