---
StoryRender:
  actAs:
    yiggEpoch:
    Timestampable:
      updated:
        disabled: true
      created:
        name: created_at
        type: timestamp
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(11)
    story_id:
      type: integer(11)
      notnull: true
    user_id:
      type: integer(11)
      notnull: true
    created_at:
      notnull: true
      type: timestamp(25)
    epoch_time:
      notnull: true
      type: float
  relations:
    Story:
      local: story_id
      foreign: id
      type: one
    User:
      local: user_id
      foreign: id
      type: one
  options:
    collate: utf8_unicode_ci
    charset: utf8
  indexes:
    story_render_created_at:
      fields: created_at
    story_render_epoch_time:
      fields: epoch_time
      sorting: DESC