Story:
  actAs:
    Sluggable:
      unique: true
      fields: [title]
      length: 128
      name: internal_url
    yiggDescription:
    yiggSoftDelete:
    yiggEpoch:
    yiggTaggable:
    Timestampable:
      updated:
        name: last_edited
        type: timestamp
      created:
        name: created_at
        type: timestamp
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(11)
    title:
      notnull: true
      type: string(128)
    internal_url:
      notnull: true
      type: string(128)
      unique: true
    external_url:
      type: string(255)
    description:
      notnull: true
      type: string(1000000)
    type:
      notnull: true
      type: integer
      default: 0
    user_id:
      notnull: true
      type: integer(11)
    domain_id:
      type: integer(20)
  relations:
    StoryTag:
      class: StoryTag      
      local: id
      foreign: story_id     
      type: many
    Author:
      class: User
      local: user_id
      foreign: id
      type: one
    Ratings:
      class: Rating
      refClass: StoryRating
      foreignAlias: Story
      type: many
    Domain:
      local: domain_id
      foreign: id
      type: one
    Renders:
      class: StoryRender
      local: id
      foreign: story_id
      type: many
    Comments:
      class: Comment
      refClass: StoryComment
      foreignAlias: Story
    Tags:
      class: Tag
      refClass: StoryTag
      local: id
      foreign: story_id
      foreignAlias: Story
      type: many
    Tweets:
      class: Tweet
      refClass: StoryTweet
      foreignAlias: Story
    History:
      local: id
      foreign: story_id
      type: many
  options:
    collate: utf8_unicode_ci
    charset: utf8
  indexes:
    story_internal_url:
      fields: internal_url
    story_external_url:
      fields: external_url
    story_created_at:
      fields: created_at
    story_epoch_time:
      fields: epoch_time
      sorting: DESC
    story_is_deleted:
      fields: deleted_at

StoryIndex:
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(11)
    title:
      notnull: true
      type: string(128)
    external_url:
      type: string(500)
    description:
      notnull: true
      type: string(1000000)

History:
  actAs:
    yiggNotifcation:
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(11)
    story_id:
      type: integer(11)
    user_id:
      type: integer(11)
    created_at:
      type: timestamp(25)
  relations:
    Story:
      local: story_id
      foreign: id
      type: one
    User:
      local: user_id
      foreign: id
      type: one
  options:
    collate: utf8_unicode_ci
    charset: utf8
  indexes:
    history_created_at:
      fields: created_at