StoryTag:
  actAs: [yiggMultipleReference]
  columns:
    id:
      primary: true
      autoincrement: true
      notnull: true
      type: integer(11)
    story_id:
      notnull: true
      type: int(11)
    tag_id:
      notnull: true
      type: int(11)
  relations:
    StoryTag:
      class: StoryTag      
      local: tag_id
      foreign: tag_id     
      type: many
    Story:
      class: Story
      refClass: StoryTag
      local: id
      foreign: story_id
      foreignAlias: Story
      type: many
  options:
    collate: utf8_unicode_ci
    charset: utf8